/*
 * Maintained by jemo on 2020.11.19 to now 15:09:21
 * Created by jemo on 2020.11.19 15:09:21
 * pdd ad hourly data
 */

package database

const createPddAdHourlyData = `
  CREATE TABLE IF NOT EXISTS pddAdHourlyData (
    entityId INTEGER UNSIGNED NOT NULL,
    date DATE NOT NULL,
    hour TINYINT UNSIGNED NOT NULL,
    mallId INTEGER UNSIGNED,
    planId INTEGER UNSIGNED,
    unitId INTEGER UNSIGNED,
    scenesType TINYINT UNSIGNED,
    appActivateNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    appActivateRate FLOAT UNSIGNED NOT NULL DEFAULT 0,
    appPayNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    appRegisterNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    avgPayAmount INTEGER UNSIGNED NOT NULL DEFAULT 0,
    click INTEGER UNSIGNED NOT NULL COMMENT '点击量',
    costPerAppActivate INTEGER UNSIGNED NOT NULL DEFAULT 0,
    costPerAppPay INTEGER UNSIGNED NOT NULL DEFAULT 0,
    costPerAppRegister INTEGER UNSIGNED NOT NULL DEFAULT 0,
    costPerFormSubmit INTEGER UNSIGNED NOT NULL DEFAULT 0,
    costPerLeadOrder INTEGER UNSIGNED NOT NULL DEFAULT 0,
    costPerMallFav INTEGER UNSIGNED NOT NULL DEFAULT 0,
    cpc FLOAT UNSIGNED NOT NULL COMMENT 'Cost Per Click 平均点击花费(厘)',
    cpm FLOAT UNSIGNED NOT NULL COMMENT '千次曝光花费(厘)',
    ctr FLOAT UNSIGNED NOT NULL COMMENT '点击率',
    cvr FLOAT UNSIGNED NOT NULL COMMENT 'Click Conversion Rate 点击转化率',
    formSubmitNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    gmv INTEGER UNSIGNED NOT NULL COMMENT '交易额(厘)',
    goodsFavNum INTEGER UNSIGNED NOT NULL COMMENT '商品收藏量',
    impression INTEGER UNSIGNED NOT NULL COMMENT '曝光量',
    inquiryNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    leadOrderNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    liveClickNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    liveCommentNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    liveShareNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    mallFavNum INTEGER UNSIGNED NOT NULL COMMENT '店铺关注量',
    mallFavRate FLOAT UNSIGNED NOT NULL DEFAULT 0,
    nonCommercialCVR INTEGER UNSIGNED NOT NULL DEFAULT 0,
    nonFanClickNum INTEGER UNSIGNED NOT NULL DEFAULT 0,
    nonFanSpend INTEGER UNSIGNED NOT NULL DEFAULT 0,
    orderNum INTEGER UNSIGNED NOT NULL COMMENT '订单量',
    rankAverage INTEGER UNSIGNED NOT NULL DEFAULT 0,
    rankMedian INTEGER UNSIGNED NOT NULL DEFAULT 0,
    roi FLOAT UNSIGNED NOT NULL COMMENT '投入产出比',
    spend INTEGER UNSIGNED NOT NULL COMMENT '花费(厘)',
    spendWithSdk INTEGER UNSIGNED NOT NULL COMMENT '花费(厘)',
    transactionCost INTEGER UNSIGNED NOT NULL COMMENT '交易花费(分)',
    uniqueView INTEGER UNSIGNED NOT NULL DEFAULT 0,
    INDEX pddAdHourlyDataIndex (entityId, date, hour)
  );
`
